# Protobuf + gRPC stubs for the Helloworld service (single-file example).
#
# In real projects, generate message types and gRPC stubs separately:
#
#   crystal build ../proto.cr/src/protoc-gen-crystal_main.cr -o bin/protoc-gen-crystal
#   crystal build src/protoc-gen-crystal-grpc_main.cr -o bin/protoc-gen-crystal-grpc
#
#   protoc --plugin=protoc-gen-crystal=bin/protoc-gen-crystal \
#          --crystal_out=. helloworld.proto
#
#   protoc --plugin=protoc-gen-crystal-grpc=bin/protoc-gen-crystal-grpc \
#          --crystal-grpc_out=. helloworld.proto
#
# Proto definition:
#   package helloworld;
#   service Greeter {
#     rpc SayHello (HelloRequest) returns (HelloReply) {}
#   }
#   message HelloRequest { string name = 1; }
#   message HelloReply   { string message = 1; }

require "../../src/grpc"

module Helloworld
  # --- Minimal protobuf helpers ---
  # Encodes/decodes a single string field using protobuf wire format.
  module Proto
    def self.encode_string_field(field : Int32, value : String) : Bytes
      io = IO::Memory.new
      encode_varint(io, ((field << 3) | 2).to_u64)
      encode_varint(io, value.bytesize.to_u64)
      io.write(value.to_slice)
      io.to_slice
    end

    def self.decode_string_field(data : Bytes, target_field : Int32) : String?
      i = 0
      while i < data.size
        tag, consumed = decode_varint(data, i)
        i += consumed
        field_number = (tag >> 3).to_i
        wire_type = (tag & 0x7).to_i
        case wire_type
        when 0
          _, consumed = decode_varint(data, i)
          i += consumed
        when 2
          len, consumed = decode_varint(data, i)
          i += consumed
          return String.new(data[i, len.to_i]) if field_number == target_field
          i += len.to_i
        else
          break
        end
      end
      nil
    end

    def self.encode_varint(io : IO, value : UInt64) : Nil
      loop do
        byte = (value & 0x7F).to_u8
        value >>= 7
        if value != 0
          io.write_byte(byte | 0x80_u8)
        else
          io.write_byte(byte)
          break
        end
      end
    end

    def self.decode_varint(data : Bytes, offset : Int32) : {UInt64, Int32}
      result = 0_u64
      shift = 0
      consumed = 0
      loop do
        break if offset + consumed >= data.size
        byte = data[offset + consumed].to_u64
        consumed += 1
        result |= (byte & 0x7F) << shift
        shift += 7
        break unless (byte & 0x80) != 0
      end
      {result, consumed}
    end
  end

  # --- Message types ---

  struct HelloRequest
    property name : String

    def initialize(@name : String = "")
    end

    def encode : Bytes
      Proto.encode_string_field(1, @name)
    end

    def self.decode(data : Bytes) : HelloRequest
      new(Proto.decode_string_field(data, 1) || "")
    end
  end

  struct HelloReply
    property message : String

    def initialize(@message : String = "")
    end

    def encode : Bytes
      Proto.encode_string_field(1, @message)
    end

    def self.decode(data : Bytes) : HelloReply
      new(Proto.decode_string_field(data, 1) || "")
    end
  end

  # --- Generated service base and client ---
  # (In production code, protoc-gen-crystal-grpc generates this section.
  #  Message structs are generated by protoc-gen-crystal.)

  module Greeter
    FULL_NAME = "helloworld.Greeter"

    # Service is the generated abstract base class for server implementations.
    # Users subclass this and implement each RPC method.
    abstract class Service < GRPC::Service
      def service_full_name : String
        FULL_NAME
      end

      abstract def say_hello(request : HelloRequest, ctx : GRPC::ServerContext) : HelloReply

      def dispatch(method : String, body : Bytes, ctx : GRPC::ServerContext) : {Bytes, GRPC::Status}
        case method
        when "SayHello"
          req = HelloRequest.decode(body)
          resp = say_hello(req, ctx)
          {resp.encode, GRPC::Status.ok}
        else
          {Bytes.empty, GRPC::Status.unimplemented("method #{method} not found")}
        end
      rescue ex : GRPC::StatusError
        {Bytes.empty, ex.status}
      rescue ex
        {Bytes.empty, GRPC::Status.internal(ex.message || "internal error")}
      end
    end

    # Client is the generated type-safe client stub.
    class Client
      def initialize(@channel : GRPC::Channel)
      end

      def say_hello(
        request : HelloRequest,
        metadata : (Hash(String, String) | GRPC::Metadata)? = nil,
        deadline : Time::Span | Time? = nil,
        ctx : GRPC::ClientContext? = nil,
      ) : HelloReply
        call_ctx = ctx || GRPC::ClientContext.new(
          metadata: metadata || GRPC::Metadata.new,
          deadline: deadline
        )
        response = @channel.unary_call(FULL_NAME, "SayHello", request.encode, call_ctx)
        raise GRPC::StatusError.new(response.status, response.trailing_metadata) unless response.status.ok?
        HelloReply.decode(response.raw)
      end
    end
  end
end
