# Protobuf stubs for the Helloworld service.
# In a real project these are generated by protoc-gen-crystal-grpc:
#
#   crystal build src/protoc-gen-crystal-grpc.cr -o bin/protoc-gen-crystal-grpc
#   protoc --plugin=protoc-gen-crystal-grpc=bin/protoc-gen-crystal-grpc \
#          --crystal-grpc_out=. helloworld.proto
#
# Proto definition:
#   package helloworld;
#   service Greeter {
#     rpc SayHello (HelloRequest) returns (HelloReply) {}
#   }
#   message HelloRequest { string name = 1; }
#   message HelloReply   { string message = 1; }

require "../../src/grpc"

module Helloworld
  # --- Minimal protobuf helpers ---
  # Encodes/decodes a single string field using protobuf wire format.
  module Proto
    def self.encode_string_field(field : Int32, value : String) : Bytes
      io = IO::Memory.new
      encode_varint(io, ((field << 3) | 2).to_u64)
      encode_varint(io, value.bytesize.to_u64)
      io.write(value.to_slice)
      io.to_slice
    end

    def self.decode_string_field(data : Bytes, target_field : Int32) : String?
      i = 0
      while i < data.size
        tag, consumed = decode_varint(data, i)
        i += consumed
        field_number = (tag >> 3).to_i
        wire_type = (tag & 0x7).to_i
        case wire_type
        when 0
          _, consumed = decode_varint(data, i)
          i += consumed
        when 2
          len, consumed = decode_varint(data, i)
          i += consumed
          return String.new(data[i, len.to_i]) if field_number == target_field
          i += len.to_i
        else
          break
        end
      end
      nil
    end

    def self.encode_varint(io : IO, value : UInt64) : Nil
      loop do
        byte = (value & 0x7F).to_u8
        value >>= 7
        if value != 0
          io.write_byte(byte | 0x80_u8)
        else
          io.write_byte(byte)
          break
        end
      end
    end

    def self.decode_varint(data : Bytes, offset : Int32) : {UInt64, Int32}
      result = 0_u64
      shift = 0
      consumed = 0
      loop do
        break if offset + consumed >= data.size
        byte = data[offset + consumed].to_u64
        consumed += 1
        result |= (byte & 0x7F) << shift
        shift += 7
        break unless (byte & 0x80) != 0
      end
      {result, consumed}
    end
  end

  # --- Message types ---

  struct HelloRequest
    property name : String

    def initialize(@name : String = "")
    end

    def to_proto : Bytes
      Proto.encode_string_field(1, @name)
    end

    def self.from_proto(data : Bytes) : HelloRequest
      new(Proto.decode_string_field(data, 1) || "")
    end
  end

  struct HelloReply
    property message : String

    def initialize(@message : String = "")
    end

    def to_proto : Bytes
      Proto.encode_string_field(1, @message)
    end

    def self.from_proto(data : Bytes) : HelloReply
      new(Proto.decode_string_field(data, 1) || "")
    end
  end

  # --- Generated service base and client ---
  # (In production code, protoc-gen-crystal-grpc generates this section.)

  SERVICE_NAME = "helloworld.Greeter"

  # GreeterService is the generated abstract base class for server implementations.
  # Users subclass this and implement each RPC method.
  abstract class GreeterService < GRPC::Service
    def service_name : String
      SERVICE_NAME
    end

    abstract def say_hello(request : HelloRequest, ctx : GRPC::ServerContext) : HelloReply

    def dispatch(method : String, body : Bytes, ctx : GRPC::ServerContext) : {Bytes, GRPC::Status}
      case method
      when "SayHello"
        req = HelloRequest.from_proto(body)
        resp = say_hello(req, ctx)
        {resp.to_proto, GRPC::Status.ok}
      else
        {Bytes.empty, GRPC::Status.unimplemented("method #{method} not found")}
      end
    rescue ex : GRPC::StatusError
      {Bytes.empty, ex.status}
    rescue ex
      {Bytes.empty, GRPC::Status.internal(ex.message || "internal error")}
    end
  end

  # GreeterClient is the generated type-safe client stub.
  class GreeterClient
    def initialize(@channel : GRPC::Channel)
    end

    def say_hello(
      request : HelloRequest,
      metadata : (Hash(String, String) | GRPC::Metadata)? = nil,
      deadline : Time::Span | Time? = nil,
      ctx : GRPC::ClientContext? = nil,
    ) : HelloReply
      call_ctx = ctx || GRPC::ClientContext.new(
        metadata: metadata || GRPC::Metadata.new,
        deadline: deadline
      )
      body, status = @channel.unary_call(SERVICE_NAME, "SayHello", request.to_proto, call_ctx)
      raise GRPC::StatusError.new(status) unless status.ok?
      HelloReply.from_proto(body)
    end
  end
end
