module GRPC
  module Generator
    # TypeNameResolver abstracts proto fully-qualified type to Crystal constant
    # resolution so the grpc generator can use a single naming authority.
    abstract class TypeNameResolver
      abstract def resolve(proto_type : String, current_package : String) : String
    end

    # CanonicalTypeNameResolver follows protobuf naming semantics:
    # - package segments are snake_case -> CamelCase
    # - type segments are preserved
    # - types in current_package are emitted relative to that package
    class CanonicalTypeNameResolver < TypeNameResolver
      def resolve(proto_type : String, current_package : String) : String
        normalized = proto_type.lstrip('.')
        parts = normalized.split('.')
        return normalized if parts.empty?

        package_parts = [] of String
        type_parts = [] of String
        parts.each do |part|
          if type_parts.empty? && part[0]?.try(&.lowercase?)
            package_parts << part
          else
            type_parts << part
          end
        end

        package_name = package_parts.join('.')
        crystal_package = package_parts.map { |part| camelize(part) }

        if !current_package.empty? && package_name == current_package
          return type_parts.join("::")
        end

        (crystal_package + type_parts).join("::")
      end

      private def camelize(s : String) : String
        s.split('_').map(&.capitalize).join
      end
    end

    # TypeMapNameResolver delegates type resolution to an externally provided
    # map generated by the protobuf naming authority.
    class TypeMapNameResolver < TypeNameResolver
      def initialize(@map : Hash(String, String))
      end

      def resolve(proto_type : String, current_package : String) : String
        if mapped = @map[proto_type]?
          return mapped
        end

        raise ArgumentError.new("Missing type_map entry for #{proto_type}")
      end
    end
  end
end
