#!/usr/bin/env crystal
# protoc-gen-crystal-grpc — protoc plugin that generates Crystal gRPC service stubs.
#
# For each .proto file passed by protoc the plugin emits a .grpc.cr file with:
#   * An abstract GRPC::Service subclass for the server side
#   * A typed client stub class
#
# All four RPC streaming variants are supported:
#   unary, server-streaming, client-streaming, bidirectional-streaming
#
# Usage:
#   protoc --crystal-grpc_out=OUTPUT_DIR \
#          --plugin=protoc-gen-crystal-grpc \
#          path/to/service.proto
#
# The plugin expects message types to already be available in the generated
# output (e.g. from protoc-gen-crystal).  It only emits service infrastructure.

require "proto"

alias PluginCodeGeneratorRequest = Proto::Bootstrap::CodeGeneratorRequest
alias ProtoFileDescriptor = Proto::Bootstrap::FileDescriptorProto
alias ServiceDescriptor = Proto::Bootstrap::ServiceDescriptorProto
alias MethodDescriptor = Proto::Bootstrap::MethodDescriptorProto

class MethodDescriptor
  def rpc_type : Symbol
    case {client_streaming?, server_streaming?}
    when {false, false} then :unary
    when {false, true}  then :server_streaming
    when {true, false}  then :client_streaming
    else                     :bidi
    end
  end
end

# ---------------------------------------------------------------------------
# Crystal gRPC code generator
# ---------------------------------------------------------------------------

class CrystalGrpcCodeGenerator
  @resolver : Proto::Generator::TypeNameResolver

  def initialize
    @resolver = Proto::Generator::CanonicalTypeNameResolver.new
  end

  # Entry point: process the request and return an encoded CodeGeneratorResponse.
  def run(request : PluginCodeGeneratorRequest) : Bytes
    @resolver = Proto::Generator::TypeNameResolver.build(request.parameter, request.proto_file)

    file_index = {} of String => ProtoFileDescriptor
    request.proto_file.each { |file_desc| file_index[file_desc.name] = file_desc }

    generated = [] of {String, String}
    request.file_to_generate.each do |proto_name|
      fd = file_index[proto_name]?
      next unless fd
      next if fd.service.empty?
      content = generate_file(fd)
      output_name = proto_name.sub(/\.proto$/, ".grpc.cr")
      generated << {output_name, content}
    end

    encode_response(generated)
  end

  # ---- File-level generation ----

  private def generate_file(fd : ProtoFileDescriptor) : String
    String.build do |str|
      str << "# Code generated by protoc-gen-crystal-grpc. DO NOT EDIT.\n"
      str << "# Source: #{fd.name}\n"
      str << "#\n"
      str << "# Requires message types to be available (e.g. from a .pb.cr file).\n"
      str << "# Add `require \"grpc\"` and the corresponding message file before\n"
      str << "# requiring this file.\n"
      str << "\n"

      mod = package_to_module(fd.package)
      if mod
        str << "module #{mod}\n"
        fd.service.each { |svc| generate_service_pair(str, svc, fd, "  ") }
        str << "end\n"
      else
        fd.service.each { |svc| generate_service_pair(str, svc, fd, "") }
      end
    end
  end

  # Emit both the abstract service class and the client stub for one service.
  private def generate_service_pair(str : String::Builder, svc : ServiceDescriptor,
                                    fd : ProtoFileDescriptor, indent : String) : Nil
    full_name = full_service_name(fd, svc)

    str << "\n"
    str << "#{indent}module #{svc.name}\n"
    str << "#{indent}  FULL_NAME = #{full_name.inspect}\n"
    generate_service_class(str, svc, fd, indent + "  ")
    str << "\n"
    generate_client_class(str, svc, fd, indent + "  ")
    str << "#{indent}end\n"
  end

  # ---- Abstract service (server side) ----

  private def generate_service_class(str : String::Builder, svc : ServiceDescriptor,
                                     fd : ProtoFileDescriptor, indent : String) : Nil
    str << "\n"
    str << "#{indent}# Service is the generated abstract base class for server implementations.\n"
    str << "#{indent}# Subclass it and implement each RPC method, then register with GRPC::Server#handle.\n"
    str << "#{indent}abstract class Service < GRPC::Service\n"
    str << "\n"
    str << "#{indent}  def service_full_name : String\n"
    str << "#{indent}    FULL_NAME\n"
    str << "#{indent}  end\n"
    str << "\n"
    str << "#{indent}  # Override this hook to swap marshaller implementations.\n"
    str << "#{indent}  protected def marshaller_for(type : T.class) : GRPC::Marshaller(T) forall T\n"
    str << "#{indent}    GRPC::ProtoMarshaller(T).new\n"
    str << "#{indent}  end\n"

    # Abstract method declarations
    str << "\n"
    svc.method.each do |meth|
      input = resolve_type(meth.input_type, fd.package)
      output = resolve_type(meth.output_type, fd.package)
      mname = to_snake_case(meth.name)
      case meth.rpc_type
      when :unary
        str << "#{indent}  abstract def #{mname}(request : #{input}, ctx : GRPC::ServerContext) : #{output}\n"
      when :server_streaming
        str << "#{indent}  abstract def #{mname}(request : #{input}, writer : GRPC::ResponseStream(#{output}), ctx : GRPC::ServerContext) : GRPC::Status\n"
      when :client_streaming
        str << "#{indent}  abstract def #{mname}(requests : GRPC::RequestStream(#{input}), ctx : GRPC::ServerContext) : #{output}\n"
      when :bidi
        str << "#{indent}  abstract def #{mname}(requests : GRPC::RequestStream(#{input}), writer : GRPC::ResponseStream(#{output}), ctx : GRPC::ServerContext) : GRPC::Status\n"
      end
    end

    # dispatch (unary)
    unary = svc.method.select { |meth| meth.rpc_type == :unary }
    str << "\n"
    str << "#{indent}  def dispatch(method : String, body : Bytes, ctx : GRPC::ServerContext) : {Bytes, GRPC::Status}\n"
    if unary.empty?
      str << "#{indent}    {Bytes.empty, GRPC::Status.unimplemented(\"method \#{method} not found\")}\n"
    else
      str << "#{indent}    case method\n"
      unary.each do |meth|
        input = resolve_type(meth.input_type, fd.package)
        output = resolve_type(meth.output_type, fd.package)
        mname = to_snake_case(meth.name)
        str << "#{indent}    when #{meth.name.inspect}\n"
        str << "#{indent}      req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}      res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}      req  = req_marshaller.decode(body)\n"
        str << "#{indent}      resp = #{mname}(req, ctx)\n"
        str << "#{indent}      {res_marshaller.encode(resp), GRPC::Status.ok}\n"
      end
      str << "#{indent}    else\n"
      str << "#{indent}      {Bytes.empty, GRPC::Status.unimplemented(\"method \#{method} not found\")}\n"
      str << "#{indent}    end\n"
    end
    str << "#{indent}  rescue ex : GRPC::StatusError\n"
    str << "#{indent}    {Bytes.empty, ex.status}\n"
    str << "#{indent}  rescue ex\n"
    str << "#{indent}    {Bytes.empty, GRPC::Status.internal(ex.message || \"internal error\")}\n"
    str << "#{indent}  end\n"

    # server_streaming? + dispatch_server_stream
    ss = svc.method.select { |meth| meth.rpc_type == :server_streaming }
    unless ss.empty?
      str << "\n"
      emit_streaming_predicate(str, "server_streaming?", ss, indent)
      str << "\n"
      str << "#{indent}  def dispatch_server_stream(method : String, body : Bytes,\n"
      str << "#{indent}                             ctx : GRPC::ServerContext,\n"
      str << "#{indent}                             writer : GRPC::RawResponseStream) : GRPC::Status\n"
      str << "#{indent}    case method\n"
      ss.each do |meth|
        input = resolve_type(meth.input_type, fd.package)
        output = resolve_type(meth.output_type, fd.package)
        mname = to_snake_case(meth.name)
        str << "#{indent}    when #{meth.name.inspect}\n"
        str << "#{indent}      req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}      res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}      typed_writer = GRPC::ResponseStream(#{output}).new(writer, res_marshaller)\n"
        str << "#{indent}      #{mname}(req_marshaller.decode(body), typed_writer, ctx)\n"
      end
      str << "#{indent}    else\n"
      str << "#{indent}      GRPC::Status.unimplemented(\"method \#{method} not found\")\n"
      str << "#{indent}    end\n"
      str << "#{indent}  rescue ex : GRPC::StatusError\n"
      str << "#{indent}    ex.status\n"
      str << "#{indent}  rescue ex\n"
      str << "#{indent}    GRPC::Status.internal(ex.message || \"internal error\")\n"
      str << "#{indent}  end\n"
    end

    # client_streaming? + dispatch_client_stream
    cs = svc.method.select { |meth| meth.rpc_type == :client_streaming }
    unless cs.empty?
      emit_streaming_predicate(str, "client_streaming?", cs, indent)
      str << "\n"
      str << "#{indent}  def dispatch_client_stream(method : String, requests : GRPC::RawRequestStream,\n"
      str << "#{indent}                             ctx : GRPC::ServerContext) : {Bytes, GRPC::Status}\n"
      str << "#{indent}    case method\n"
      cs.each do |meth|
        input = resolve_type(meth.input_type, fd.package)
        output = resolve_type(meth.output_type, fd.package)
        mname = to_snake_case(meth.name)
        str << "#{indent}    when #{meth.name.inspect}\n"
        str << "#{indent}      req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}      res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}      reqs = GRPC::RequestStream(#{input}).new(requests.ch, req_marshaller)\n"
        str << "#{indent}      resp = #{mname}(reqs, ctx)\n"
        str << "#{indent}      {res_marshaller.encode(resp), GRPC::Status.ok}\n"
      end
      str << "#{indent}    else\n"
      str << "#{indent}      {Bytes.empty, GRPC::Status.unimplemented(\"method \#{method} not found\")}\n"
      str << "#{indent}    end\n"
      str << "#{indent}  rescue ex : GRPC::StatusError\n"
      str << "#{indent}    {Bytes.empty, ex.status}\n"
      str << "#{indent}  rescue ex\n"
      str << "#{indent}    {Bytes.empty, GRPC::Status.internal(ex.message || \"internal error\")}\n"
      str << "#{indent}  end\n"
    end

    # bidi_streaming? + dispatch_bidi_stream
    bidi = svc.method.select { |meth| meth.rpc_type == :bidi }
    unless bidi.empty?
      emit_streaming_predicate(str, "bidi_streaming?", bidi, indent)
      str << "\n"
      str << "#{indent}  def dispatch_bidi_stream(method : String, requests : GRPC::RawRequestStream,\n"
      str << "#{indent}                           ctx : GRPC::ServerContext,\n"
      str << "#{indent}                           writer : GRPC::RawResponseStream) : GRPC::Status\n"
      str << "#{indent}    case method\n"
      bidi.each do |meth|
        input = resolve_type(meth.input_type, fd.package)
        output = resolve_type(meth.output_type, fd.package)
        mname = to_snake_case(meth.name)
        str << "#{indent}    when #{meth.name.inspect}\n"
        str << "#{indent}      req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}      res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}      reqs = GRPC::RequestStream(#{input}).new(requests.ch, req_marshaller)\n"
        str << "#{indent}      typed_writer = GRPC::ResponseStream(#{output}).new(writer, res_marshaller)\n"
        str << "#{indent}      #{mname}(reqs, typed_writer, ctx)\n"
      end
      str << "#{indent}    else\n"
      str << "#{indent}      GRPC::Status.unimplemented(\"method \#{method} not found\")\n"
      str << "#{indent}    end\n"
      str << "#{indent}  rescue ex : GRPC::StatusError\n"
      str << "#{indent}    ex.status\n"
      str << "#{indent}  rescue ex\n"
      str << "#{indent}    GRPC::Status.internal(ex.message || \"internal error\")\n"
      str << "#{indent}  end\n"
    end

    str << "#{indent}end\n"
  end

  # ---- Client stub ----

  private def generate_client_class(str : String::Builder, svc : ServiceDescriptor,
                                    fd : ProtoFileDescriptor, indent : String) : Nil
    str << "#{indent}# Client is the generated type-safe client stub.\n"
    str << "#{indent}# Create one per GRPC::Channel and reuse across calls.\n"
    str << "#{indent}class Client\n"
    str << "#{indent}  def initialize(@channel : GRPC::Channel)\n"
    str << "#{indent}  end\n"
    str << "\n"
    str << "#{indent}  # Override this hook to swap marshaller implementations.\n"
    str << "#{indent}  protected def marshaller_for(type : T.class) : GRPC::Marshaller(T) forall T\n"
    str << "#{indent}    GRPC::ProtoMarshaller(T).new\n"
    str << "#{indent}  end\n"

    svc.method.each do |meth|
      input = resolve_type(meth.input_type, fd.package)
      output = resolve_type(meth.output_type, fd.package)
      mname = to_snake_case(meth.name)
      sname = "FULL_NAME"
      str << "\n"
      case meth.rpc_type
      when :unary
        str << "#{indent}  def #{mname}(request : #{input}, ctx : GRPC::ClientContext = GRPC::ClientContext.new) : #{output}\n"
        str << "#{indent}    #{mname}_response(request, ctx).ok!\n"
        str << "#{indent}  end\n"
        str << "\n"
        str << "#{indent}  def #{mname}_response(request : #{input}, ctx : GRPC::ClientContext = GRPC::ClientContext.new) : GRPC::UnaryResponse(#{output})\n"
        str << "#{indent}    req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}    res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}    response = @channel.unary_call(#{sname}, #{meth.name.inspect}, req_marshaller.encode(request), ctx)\n"
        str << "#{indent}    message = response.raw.empty? ? nil : res_marshaller.decode(response.raw)\n"
        str << "#{indent}    GRPC::UnaryResponse(#{output}).new(message, response.initial_metadata, response.trailing_metadata, response.status)\n"
        str << "#{indent}  end\n"
      when :server_streaming
        str << "#{indent}  def #{mname}(request : #{input}, ctx : GRPC::ClientContext = GRPC::ClientContext.new) : GRPC::ServerStream(#{output})\n"
        str << "#{indent}    req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}    res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}    raw    = @channel.open_server_stream(#{sname}, #{meth.name.inspect}, req_marshaller.encode(request), ctx)\n"
        str << "#{indent}    stream = GRPC::ServerStream(#{output}).new(-> { raw.headers }, -> { raw.status }, -> { raw.trailers }, -> { raw.cancel })\n"
        str << "#{indent}    spawn do\n"
        str << "#{indent}      begin\n"
        str << "#{indent}        raw.each { |bytes| stream.push(res_marshaller.decode(bytes)) }\n"
        str << "#{indent}        stream.finish\n"
        str << "#{indent}      rescue ex\n"
        str << "#{indent}        stream.finish(GRPC::Status.internal(ex.message || \"error\"))\n"
        str << "#{indent}      end\n"
        str << "#{indent}    end\n"
        str << "#{indent}    stream\n"
        str << "#{indent}  end\n"
      when :client_streaming
        str << "#{indent}  # #{mname} opens a client-streaming RPC.\n"
        str << "#{indent}  # Send messages via the returned ClientStream, then call close_and_recv\n"
        str << "#{indent}  # to flush and receive the server's single response.\n"
        str << "#{indent}  def #{mname}(ctx : GRPC::ClientContext = GRPC::ClientContext.new) : GRPC::ClientStream(#{input}, #{output})\n"
        str << "#{indent}    raw = @channel.open_client_stream_live(#{sname}, #{meth.name.inspect}, ctx)\n"
        str << "#{indent}    req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}    res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}    result_chan = ::Channel(#{output} | Exception).new(1)\n"
        str << "#{indent}    send_proc = Proc(#{input}, Nil).new { |msg| raw.send_raw(req_marshaller.encode(msg)) }\n"
        str << "#{indent}    close_proc = Proc(Nil).new {\n"
        str << "#{indent}      spawn do\n"
        str << "#{indent}        begin\n"
        str << "#{indent}          body = raw.close_and_recv\n"
        str << "#{indent}          st = raw.status\n"
        str << "#{indent}          if st.ok?\n"
        str << "#{indent}            result_chan.send(res_marshaller.decode(body)) rescue nil\n"
        str << "#{indent}          else\n"
        str << "#{indent}            result_chan.send(GRPC::StatusError.new(st, raw.trailers)) rescue nil\n"
        str << "#{indent}          end\n"
        str << "#{indent}        rescue ex\n"
        str << "#{indent}          result_chan.send(ex) rescue nil\n"
        str << "#{indent}        end\n"
        str << "#{indent}      end\n"
        str << "#{indent}    }\n"
        str << "#{indent}    GRPC::ClientStream(#{input}, #{output}).new(send_proc, close_proc, result_chan, -> { raw.headers }, -> { raw.status }, -> { raw.trailers }, -> { raw.cancel })\n"
        str << "#{indent}  end\n"
      when :bidi
        str << "#{indent}  # #{mname} opens a bidirectional-streaming RPC.\n"
        str << "#{indent}  # Send messages via the returned BidiCall, then call close_send to\n"
        str << "#{indent}  # signal end-of-input and iterate the replies with #each.\n"
        str << "#{indent}  def #{mname}(ctx : GRPC::ClientContext = GRPC::ClientContext.new) : GRPC::BidiCall(#{input}, #{output})\n"
        str << "#{indent}    raw = @channel.open_bidi_stream_live(#{sname}, #{meth.name.inspect}, ctx)\n"
        str << "#{indent}    req_marshaller = marshaller_for(#{input})\n"
        str << "#{indent}    res_marshaller = marshaller_for(#{output})\n"
        str << "#{indent}    recv_chan = ::Channel(#{output} | Exception).new(128)\n"
        str << "#{indent}    spawn do\n"
        str << "#{indent}      begin\n"
        str << "#{indent}        raw.each { |bytes| recv_chan.send(res_marshaller.decode(bytes)) rescue nil }\n"
        str << "#{indent}        recv_chan.close\n"
        str << "#{indent}      rescue ex\n"
        str << "#{indent}        recv_chan.send(ex) rescue nil\n"
        str << "#{indent}        recv_chan.close rescue nil\n"
        str << "#{indent}      end\n"
        str << "#{indent}    end\n"
        str << "#{indent}    send_proc = Proc(#{input}, Nil).new { |msg| raw.send_raw(req_marshaller.encode(msg)) }\n"
        str << "#{indent}    close_proc = Proc(Nil).new { raw.close_send }\n"
        str << "#{indent}    GRPC::BidiCall(#{input}, #{output}).new(send_proc, close_proc, recv_chan, -> { raw.headers }, -> { raw.status }, -> { raw.trailers }, -> { raw.cancel })\n"
        str << "#{indent}  end\n"
      end
    end

    str << "#{indent}end\n"
  end

  # ---- CodeGeneratorResponse encoder ----

  private def encode_response(files : Array({String, String})) : Bytes
    response = Proto::Bootstrap::CodeGeneratorResponse.new
    response.supported_features = Proto::Bootstrap::FEATURE_PROTO3_OPTIONAL
    files.each do |name, content|
      response_file = Proto::Bootstrap::CodeGeneratorResponseFile.new
      response_file.name = name
      response_file.content = content
      response.file << response_file
    end

    response.encode
  end

  # ---- Helpers ----

  # Convert a proto package like "google.protobuf" to "Google::Protobuf".
  private def package_to_module(package : String) : String?
    Proto::Generator::NamingPolicy.package_to_module(package)
  end

  # Convert a proto full type name like ".helloworld.HelloRequest" to a
  # Crystal type expression relative to *current_package*.
  private def resolve_type(proto_type : String, current_package : String) : String
    @resolver.resolve(proto_type, current_package)
  end

  # "SayHello" → "say_hello", "GetFooBarBaz" → "get_foo_bar_baz"
  private def to_snake_case(name : String) : String
    name
      .gsub(/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
      .gsub(/([a-z\d])([A-Z])/, "\\1_\\2")
      .downcase
  end

  # Emit a streaming predicate method that returns true for the listed RPC names.
  private def emit_streaming_predicate(str : String::Builder, method_name : String,
                                       methods : Array(MethodDescriptor), indent : String) : Nil
    str << "\n"
    str << "#{indent}  def #{method_name}(method : String) : Bool\n"
    str << "#{indent}    case method\n"
    methods.each { |meth| str << "#{indent}    when #{meth.name.inspect} then true\n" }
    str << "#{indent}    else                       false\n"
    str << "#{indent}    end\n"
    str << "#{indent}  end\n"
  end

  private def full_service_name(fd : ProtoFileDescriptor, svc : ServiceDescriptor) : String
    fd.package.empty? ? svc.name : "#{fd.package}.#{svc.name}"
  end
end
